# If set, log4rs will scan the file at the specified rate in seconds for
# changes and automatically reconfigure the logger.
refresh_rate: 30

# The "appenders" map contains the set of appenders, indexed by their names.
appenders:

  foo:

    # All appenders must specify a "kind", which will be used to look up the
    # logic to construct the appender in the `Builder` passed to the
    # deserialization function.
    kind: console

    # Filters attached to an appender are specified inside the "filters"
    # array.
    filters:

      -
        # Like appenders, filters are identified by their "kind".
        kind: threshold

        # The remainder of the configuration is passed along to the
        # filter's builder, and will vary based on the kind of filter.
        level: info

    # The remainder of the configuration is passed along to the appender's
    # builder, and will vary based on the kind of appender.
    # Appenders will commonly be associated with an encoder.
    encoder:

      # Like appenders, encoders are identified by their "kind". If no kind
      # is specified, it will default to "pattern".
      kind: pattern

      # The remainder of the configuration is passed along to the
      # encoder's builder, and will vary based on the kind of encoder.
      pattern: "{d} [{t}] {m}{n}"

# The root logger is configured by the "root" map. It is optional.
root:

  # The maximum log level for the root logger.
  level: info

  # The list of appenders attached to the root logger. Defaults to an empty
  # list if not specified.
  appenders:
    - foo

# The "loggers" map contains the set of configured loggers, indexed by their
# names.
loggers:

  foo::bar::baz:

    # The maximum log level. Defaults to the level of the logger's parent if
    # not specified.
    level: trace

    # The list of appenders attached to the logger. Defaults to an empty
    # list if not specified.
    appenders:
      - foo

    # The additivity of the logger. If true, appenders attached to the
    # logger's parent will also be attached to this logger. Defauts to true
    # if not specified.
    additive: false
